- id: enforce-action-comments
  name: Enforce Action Comments
  description: "This hook ensures that there are no comments that demand immediate action"
  entry: enforce-action-comments
  language: python
  files: ''
- id: list-action-comments
  name: List Action Comments
  description: "This hook prints out all comments with tags like FIXME and TODO"
  entry: list-action-comments
  language: python
  files: ''
- id: lfs-large-files
  name: LFS Large Files
  description: "This hooks detects binary files over a certain threshold and ensures that they are LFSed"
  entry: lfs-large-files
  language: python
  args: [ --maximum-binary-size, '524288' ] # 512 KiB
  files: ''
